config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  get "/users", to: 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  post '/users/:user_id/posts', to: 'posts#create'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_post'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  post '/users/:user_id/posts/:id', to: 'comments#create'
  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'new_comment'
  post '/users/:user_id/posts/:id/likes', to: 'likes#create', as: 'add_like'
  get '/hellos', to: 'hellos#index', as: 'hellos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  def self.recent_comments(title)
    Comment.where(post_id: Post.find_by(title:).id).order(created_at: :desc).limit(5)
  end

  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end

  validates :title, presence: true, length: { maximum: 250, too_long: '%<count>s characters is the maximum allowed' }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  attribute :posts_counter, :integer, default: 0
  attribute :photo, :string, default: '1-photo.jpg'

  def self.recent_posts(name)
    Post.where(author_id: User.find_by(name:).id).order(created_at: :desc).limit(3)
  end

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.author = current_user
    @comment.save
    redirect_to user_posts_path(current_user, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController
  def index
    render :index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = current_user.posts.find(params[:id])
    @like = Like.new
    @like.author = current_user
    @like.post = @post
    @like.save
    redirect_to user_posts_path(current_user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    # @posts = @user.posts - Replaced to avoid n+1
    @posts = @user.posts.includes(:comments, :author)
    redirect_to :root, alert: "Warning: #{@user.name} no has posts" unless @posts.length.positive?
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    render :show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    @post.save
    redirect_to user_posts_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
  <%= bootstrap_form_with model: @comment, url: user_post_path(User.find(params[:user_id])), method: :post, local: true do |f|%>
    <%= f.text_area :text %>
    <%= f.submit 'Send comment' %>
  <%end%>

app/views/comments/new.html.erb
<h1>Write a comment </h1>
<div><%= render('form')%></div>

app/views/hellos/index.html.erb
<h1>Hello Ivan</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
  <%= bootstrap_form_with model: @post, url: user_posts_path, method: :post, local: true ,layout: :horizontal , label_col: "col-sm-2", control_col: "col-sm-10" do |f|%>
    <%= f.text_field  :title %>
    <%= f.text_area :text %>
    <%= f.submit %>
  <%end%>

app/views/posts/_post_card.html.erb
<div class="post_card border">
  <h3>Post # <%= i+1 %></h3>
  <p class="text"><%= post.text %></p>
  <div class="comments">
    <button><%= link_to "Add comment", new_comment_path(current_user, post) %></button>
    <%= bootstrap_form_with(model: @like, url: add_like_path(current_user, post), method: :post, local: :true) do |f| %>
      <%= f.submit 'Like' %>
    <%end%>
    Comments: <%= post.comments_counter %>
    Likes: <%= post.likes_counter %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render('registrations/navbar') %>
<%= render 'users/user_card', user: @user %>
<ul>
  <% @posts.all.each_with_index do |post, i| %>
  <% comments = Post.recent_comments(post.title) %>
    <li><%= link_to render('post_card', post: post, i: i), user_post_path(@posts[0].author, post) %></li>
    <div class="recent_comments border">
    <h3 class="comments_tit">5 Most Recent Comments:</h3>
    <%comments.each do |comment| %>
      <li class="comment">
      <%= comment.author.name %>:
      <%= comment.text %>
      </li>
      <% end %>
    <div>
    </div>
    </div>
  <% end %>
</ul>
<div class="button border">Pagination</div>

app/views/posts/new.html.erb
<h1>Create a new post </h1>
<div><%= render('form')%></div>

app/views/posts/show.html.erb
<%= render('registrations/navbar') %>
<div class="border post_card  bio">
  <div class="post_header">
    <p> Post #<%= @post.id %> Title: <%= @post.title %>  by <%= @post.author.name%> </p>
    <p class="counters">Comments: <%= @post.comments_counter %> Likes: <%= @post.likes_counter%></p>
  </div>
  <p><%= @post.text %></p>
</div>
<div class="border recent_comments">
    <h3 class="comments_tit">All Post Comments:</h3>
    <%@comments.each do |comment| %>
      <li>
      <div>
      <%= comment.author.name %>:
      <%= comment.text %>
      </div>
      </li>
      <% end %>
</div>

app/views/users/_user_card.html.erb
  <div class="user_card">
    <div><%= image_tag user.photo, class: "user_picture" %></div>
    <div class="user_name border">
      <h2>Id:<%= user.id %>-<%= user.name%></h2>
      <p class="counters">
        <button><%= link_to "Add a post", new_post_path(user_id: user.id) %></button>
        Number of posts: <%= user.posts_counter %>
      </p>
    </div>
  </div>

app/views/users/index.html.erb
<%= render('registrations/navbar') %>
<ul id="users_list">
  <% @users.all.each do |user| %>
    <li><%= link_to(render('user_card', user: user), user_path(user)) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render('registrations/navbar') %>
<%= render 'user_card', user: @user %>
<div class="bio border">
<h3>Bio</h3>
<p><%= @user.bio %></p>
</div>
<ul>
  <% posts = User.recent_posts(@user.name) %>
  <% posts.all.each_with_index do |post, i| %>
    <li><%= link_to render('posts/post_card', post: post, i: i), user_post_path(@user, post) %></li>
  <% end %>
</ul>
<div class="button border">
<%= link_to 'See all posts', user_posts_path(@user) %>
</div>